name: israeldelcargo
description: A Flutter application for IsraelDelCargo.
publish_to: 'none' # Укажите URL, если вы планируете публиковать пакет

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Добавленные зависимости
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.7

  # Стандартные зависимости
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/playns.png
    - assets/images/about.jpg
    - assets/images/logistic.jpg
    - assets/images/logistic2.jpg
    - assets/images/logos.jpg # Добавьте логотип
    - assets/images/tovari.jpg
    - assets/images/settings.jpg